"""empty message

Revision ID: 0955094b4989
Revises: 400a79775420
Create Date: 2021-01-13 06:54:21.064034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0955094b4989'
down_revision = '400a79775420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.Unicode(), nullable=True))
    op.drop_column('item', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
