"""empty message

Revision ID: 11da9d69cc83
Revises: 627c3d1da0b8
Create Date: 2021-11-06 09:34:16.374080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11da9d69cc83'
down_revision = '627c3d1da0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('body', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'body')
    # ### end Alembic commands ###
