"""empty message

Revision ID: 12f022792826
Revises: 01d821f9e7c4
Create Date: 2022-07-30 15:22:53.148670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f022792826'
down_revision = '01d821f9e7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('txt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['txt'], ['txt.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
