"""empty message

Revision ID: 150a2112c9df
Revises: 9486f9db2694
Create Date: 2021-11-07 20:16:01.069048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150a2112c9df'
down_revision = '9486f9db2694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Unicode(), nullable=True),
    sa.Column('grade', sa.Unicode(), nullable=True),
    sa.Column('score', sa.Unicode(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
