"""empty message

Revision ID: 1d8b51741d80
Revises: d7965145af64
Create Date: 2021-11-06 10:01:49.131484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8b51741d80'
down_revision = 'd7965145af64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod', sa.Column('note_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod', 'note', ['note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mod', type_='foreignkey')
    op.drop_column('mod', 'note_id')
    # ### end Alembic commands ###
