"""empty message

Revision ID: 1eae0f00cfc6
Revises: 62cdde8c5550
Create Date: 2022-04-28 15:27:15.423073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eae0f00cfc6'
down_revision = '62cdde8c5550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('embed', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'embed')
    # ### end Alembic commands ###
