"""empty message

Revision ID: 205a147122ab
Revises: 36a5b574d17f
Create Date: 2021-03-19 00:23:17.468187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205a147122ab'
down_revision = '36a5b574d17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'seen')
    # ### end Alembic commands ###
