"""empty message

Revision ID: 2804aba6b60b
Revises: f627f01f7a45
Create Date: 2021-03-14 11:35:22.205296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2804aba6b60b'
down_revision = 'f627f01f7a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('private', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'private')
    # ### end Alembic commands ###
