"""empty message

Revision ID: 294a8155a617
Revises: 8f0769743ecb
Create Date: 2021-03-15 13:13:15.166776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294a8155a617'
down_revision = '8f0769743ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('socket_id', sa.Unicode(), nullable=True))
    op.add_column('user', sa.Column('socket_id', sa.Unicode(), nullable=True))
    op.drop_column('user', 'socketId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('socketId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'socket_id')
    op.drop_column('group', 'socket_id')
    # ### end Alembic commands ###
