"""empty message

Revision ID: 2ad12aa54e14
Revises: c6f355ba3795
Create Date: 2021-10-22 21:14:45.171454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad12aa54e14'
down_revision = 'c6f355ba3795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'socket_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('socket_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
