"""empty message

Revision ID: 2bac9c7a77a1
Revises: 4763cadd949e
Create Date: 2022-05-06 18:58:11.894702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bac9c7a77a1'
down_revision = '4763cadd949e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('text', sa.Unicode(), nullable=True))
    op.drop_column('item', 'itext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('itext', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item', 'text')
    # ### end Alembic commands ###
