"""empty message

Revision ID: 33280805bd5d
Revises: c2342ffd6af1
Create Date: 2022-01-07 23:56:33.636142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33280805bd5d'
down_revision = 'c2342ffd6af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_saved_items', sa.Column('user', sa.Integer(), nullable=True))
    op.add_column('_saved_items', sa.Column('item', sa.Integer(), nullable=True))
    op.drop_constraint('_saved_items_user_id_fkey', '_saved_items', type_='foreignkey')
    op.drop_constraint('_saved_items_item_id_fkey', '_saved_items', type_='foreignkey')
    op.create_foreign_key(None, '_saved_items', 'user', ['user'], ['id'])
    op.create_foreign_key(None, '_saved_items', 'item', ['item'], ['id'])
    op.drop_column('_saved_items', 'user_id')
    op.drop_column('_saved_items', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_saved_items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('_saved_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, '_saved_items', type_='foreignkey')
    op.drop_constraint(None, '_saved_items', type_='foreignkey')
    op.create_foreign_key('_saved_items_item_id_fkey', '_saved_items', 'item', ['item_id'], ['id'])
    op.create_foreign_key('_saved_items_user_id_fkey', '_saved_items', 'user', ['user_id'], ['id'])
    op.drop_column('_saved_items', 'item')
    op.drop_column('_saved_items', 'user')
    # ### end Alembic commands ###
