"""empty message

Revision ID: 3418cdfb9beb
Revises: f294f10f796d
Create Date: 2021-03-19 04:11:31.300901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3418cdfb9beb'
down_revision = 'f294f10f796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('unseen', sa.Boolean(), nullable=True))
    op.drop_column('room', 'seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('room', 'unseen')
    # ### end Alembic commands ###
