"""empty message

Revision ID: 34223d1c35db
Revises: 1a255c3dbd49
Create Date: 2021-05-06 07:14:54.342923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34223d1c35db'
down_revision = '1a255c3dbd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'paid')
    # ### end Alembic commands ###
