"""empty message

Revision ID: 36a5b574d17f
Revises: db3c72c316e5
Create Date: 2021-03-18 13:47:47.240570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a5b574d17f'
down_revision = 'db3c72c316e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xrooms', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xrooms', 'seen')
    # ### end Alembic commands ###
