"""empty message

Revision ID: 38f7d57002ac
Revises: 12f022792826
Create Date: 2022-08-02 01:06:38.872679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f7d57002ac'
down_revision = '12f022792826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mod_note_id_fkey', 'mod', type_='foreignkey')
    op.drop_column('mod', 'note_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mod_note_id_fkey', 'mod', 'note', ['note_id'], ['id'])
    # ### end Alembic commands ###
