"""empty message

Revision ID: 3bea9c9738c6
Revises: 5269978363cf
Create Date: 2021-10-18 10:05:41.877263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bea9c9738c6'
down_revision = '5269978363cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sitemap_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'sitemap', ['sitemap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'sitemap_id')
    # ### end Alembic commands ###
