"""empty message

Revision ID: 400a79775420
Revises: d9221da7816b
Create Date: 2021-01-12 15:50:23.157897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400a79775420'
down_revision = 'd9221da7816b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'score')
    # ### end Alembic commands ###
