"""empty message

Revision ID: 45cd6ac432a1
Revises: 8e9e00ffd002
Create Date: 2021-03-16 19:01:49.064678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45cd6ac432a1'
down_revision = '8e9e00ffd002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chats', sa.JSON(), nullable=True))
    op.drop_column('user', 'links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'chats')
    # ### end Alembic commands ###
