"""empty message

Revision ID: 4763cadd949e
Revises: 78b264c0ed71
Create Date: 2022-05-05 18:57:42.403173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4763cadd949e'
down_revision = '78b264c0ed71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('choices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'choices')
    # ### end Alembic commands ###
