"""empty message

Revision ID: 4ab51596db17
Revises: 4d6575807f74
Create Date: 2021-11-02 20:03:20.427528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab51596db17'
down_revision = '4d6575807f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('postalAddress', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('market_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'market', ['market_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'market_id')
    op.drop_table('market')
    # ### end Alembic commands ###
