"""empty message

Revision ID: 4bfbcb324f07
Revises: 95fc2943f55b
Create Date: 2021-03-13 14:20:17.341037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bfbcb324f07'
down_revision = '95fc2943f55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('code', sa.Unicode(), nullable=True))
    op.drop_column('group', 'image')
    op.add_column('user', sa.Column('code', sa.Unicode(), nullable=True))
    op.drop_column('user', 'images')
    op.drop_column('user', 'image')
    op.drop_column('user', 'hide_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hide_location', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'code')
    op.add_column('group', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('group', 'code')
    # ### end Alembic commands ###
