"""empty message

Revision ID: 4d6575807f74
Revises: 2ad12aa54e14
Create Date: 2021-10-24 20:29:33.138509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6575807f74'
down_revision = '2ad12aa54e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mod', type_='foreignkey')
    op.drop_column('mod', 'item_id')
    # ### end Alembic commands ###
