"""empty message

Revision ID: 5269978363cf
Revises: ee422bfc3d70
Create Date: 2021-10-18 10:03:31.802938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5269978363cf'
down_revision = 'ee422bfc3d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitemap', sa.Column('sitemap_index_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sitemap', 'sitemap_index', ['sitemap_index_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sitemap', type_='foreignkey')
    op.drop_column('sitemap', 'sitemap_index_id')
    # ### end Alembic commands ###
