"""empty message

Revision ID: 54153ca7aa22
Revises: c4c3d40028dd
Create Date: 2021-10-18 14:49:17.871935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54153ca7aa22'
down_revision = 'c4c3d40028dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'priority')
    # ### end Alembic commands ###
