"""empty message

Revision ID: 57cd4febc5f2
Revises: d0653ee68aaf
Create Date: 2021-02-03 23:19:55.204971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cd4febc5f2'
down_revision = 'd0653ee68aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'archived')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
