"""empty message

Revision ID: 5955a633681f
Revises: c3554cb5e9d7
Create Date: 2021-01-15 17:59:14.175892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5955a633681f'
down_revision = 'c3554cb5e9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.Unicode(), nullable=True))
        batch_op.drop_column('links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
