"""empty message

Revision ID: 597e0df562f3
Revises: 0aefaa7f893a
Create Date: 2022-07-10 19:18:26.253979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '597e0df562f3'
down_revision = '0aefaa7f893a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txt', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('txt', 'timestamp')
    op.add_column('txt_replies', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('txt_replies', 'time')
    op.add_column('txt', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('txt', 'time')
    # ### end Alembic commands ###
