"""empty message

Revision ID: 627c3d1da0b8
Revises: 1123a4f1bbb9
Create Date: 2021-11-06 00:22:10.486813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627c3d1da0b8'
down_revision = '1123a4f1bbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('role', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'author_id')
    # ### end Alembic commands ###
