"""empty message

Revision ID: 6a4681f3b437
Revises: 76bc7a195bd8
Create Date: 2021-01-11 20:38:12.912088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4681f3b437'
down_revision = '76bc7a195bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribed')
    # ### end Alembic commands ###
