"""empty message

Revision ID: 6abdcc532d15
Revises: f8aded2a661f
Create Date: 2021-01-13 19:54:20.099035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6abdcc532d15'
down_revision = 'f8aded2a661f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=True))
        batch_op.drop_column('coordinates')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('save_count')

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('save_count')
        batch_op.drop_column('location')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('save_count')

    # ### end Alembic commands ###
