"""empty message

Revision ID: 75e78de4b9cc
Revises: 40ee4ebb60fd
Create Date: 2021-03-31 07:49:56.861012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e78de4b9cc'
down_revision = '40ee4ebb60fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub', sa.Column('endpoint', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub', 'endpoint')
    # ### end Alembic commands ###
