"""empty message

Revision ID: 76bc7a195bd8
Revises: 49e41b320a71
Create Date: 2021-01-11 17:42:44.597128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bc7a195bd8'
down_revision = '49e41b320a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tags')
    op.drop_column('item', 'image_urls')
    # ### end Alembic commands ###
