"""empty message

Revision ID: 78b264c0ed71
Revises: a1a4cbdbd9e7
Create Date: 2022-05-04 15:13:01.903444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b264c0ed71'
down_revision = 'a1a4cbdbd9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'time')
    # ### end Alembic commands ###
