"""empty message

Revision ID: 7e103d002d13
Revises: 57cd4febc5f2
Create Date: 2021-02-04 09:46:31.065371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e103d002d13'
down_revision = '57cd4febc5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.Unicode(), nullable=True))
    op.add_column('item', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_column('item', 'gallery')
    op.drop_column('item', 'logo')
    op.add_column('user', sa.Column('image', sa.Unicode(), nullable=True))
    op.add_column('user', sa.Column('images', sa.Unicode(), nullable=True))
    op.drop_column('user', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'images')
    op.drop_column('user', 'image')
    op.add_column('item', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('gallery', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('item', 'images')
    op.drop_column('item', 'image')
    # ### end Alembic commands ###
