"""empty message

Revision ID: 86acbdbda56c
Revises: 9cb4f10b93b4
Create Date: 2021-10-10 15:52:26.476406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86acbdbda56c'
down_revision = '9cb4f10b93b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('no_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'no_password')
    # ### end Alembic commands ###
