"""empty message

Revision ID: 8d0d52335f20
Revises: 817db26763af
Create Date: 2021-03-20 12:35:41.386413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0d52335f20'
down_revision = '817db26763af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('value', sa.Unicode(), nullable=True))
    op.drop_column('message', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('message', 'value')
    # ### end Alembic commands ###
