"""empty message

Revision ID: 8e9e00ffd002
Revises: 294a8155a617
Create Date: 2021-03-15 15:32:05.005138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9e00ffd002'
down_revision = '294a8155a617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
