"""empty message

Revision ID: 91851506685d
Revises: 1b16124b8e8a
Create Date: 2021-03-08 05:32:21.952973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91851506685d'
down_revision = '1b16124b8e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'visible')
    # ### end Alembic commands ###
