"""empty message

Revision ID: 9486f9db2694
Revises: ca7f5a1ed8b9
Create Date: 2021-11-07 18:55:34.323175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9486f9db2694'
down_revision = 'ca7f5a1ed8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'level', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'level_id')
    # ### end Alembic commands ###
