"""empty message

Revision ID: 9b1fbb39fdef
Revises: fd11a1f01786
Create Date: 2021-02-03 01:33:55.471054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b1fbb39fdef'
down_revision = 'fd11a1f01786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('gallery', sa.JSON(), nullable=True))
    op.add_column('item', sa.Column('logo', sa.Unicode(), nullable=True))
    op.drop_column('item', 'distance')
    op.drop_column('item', 'img_urls')
    op.drop_column('item', 'paid_in')
    op.drop_column('item', 'json')
    op.drop_column('item', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('paid_in', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('img_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('item', 'logo')
    op.drop_column('item', 'gallery')
    # ### end Alembic commands ###
