"""empty message

Revision ID: 9cb4f10b93b4
Revises: 795e5b541cfe
Create Date: 2021-10-06 22:17:11.063938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb4f10b93b4'
down_revision = '795e5b541cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fields')
    # ### end Alembic commands ###
