"""empty message

Revision ID: 9ccb4dfda317
Revises: b1734ab9da1e
Create Date: 2021-01-31 20:18:26.643944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccb4dfda317'
down_revision = 'b1734ab9da1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.Unicode(), nullable=True))
    op.drop_column('user', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###
