"""empty message

Revision ID: a1a4cbdbd9e7
Revises: 1eae0f00cfc6
Create Date: 2022-04-30 10:20:35.545582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a4cbdbd9e7'
down_revision = '1eae0f00cfc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'options')
    # ### end Alembic commands ###
