"""empty message

Revision ID: a43f0cc922f1
Revises: bbeaeaab97ef
Create Date: 2022-01-06 16:07:12.292832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a43f0cc922f1'
down_revision = 'bbeaeaab97ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('one', sa.Boolean(), nullable=True))
    op.drop_column('room', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('room', 'one')
    # ### end Alembic commands ###
