"""empty message

Revision ID: ab797a1719fc
Revises: b4b597000ef3
Create Date: 2021-05-11 14:44:18.227220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab797a1719fc'
down_revision = 'b4b597000ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('last_paid', sa.DateTime(), nullable=True))
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_paid')
    op.drop_column('user', 'card')
    # ### end Alembic commands ###
