"""empty message

Revision ID: acbe2c2a954a
Revises: 2804aba6b60b
Create Date: 2021-03-14 11:37:22.094873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbe2c2a954a'
down_revision = '2804aba6b60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'links')
    # ### end Alembic commands ###
