"""empty message

Revision ID: b11f4ff2ce57
Revises: 9659246b19e8
Create Date: 2022-06-27 18:03:59.953279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11f4ff2ce57'
down_revision = '9659246b19e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('txt', sa.Column('self', sa.Boolean(), nullable=True))
    op.add_column('txt', sa.Column('personal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('txt', 'personal')
    op.drop_column('txt', 'self')
    # ### end Alembic commands ###
