"""empty message

Revision ID: b2463ea1a237
Revises: 33280805bd5d
Create Date: 2022-01-08 00:04:45.059324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2463ea1a237'
down_revision = '33280805bd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_items',
    sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item'], ['item.id'], name='saved_items_item_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='saved_items_user_fkey')
    )
    # ### end Alembic commands ###
