"""empty message

Revision ID: c3554cb5e9d7
Revises: 6abdcc532d15
Create Date: 2021-01-15 13:27:15.579786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3554cb5e9d7'
down_revision = '6abdcc532d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=123), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
