"""empty message

Revision ID: c4c3d40028dd
Revises: 3bea9c9738c6
Create Date: 2021-10-18 10:07:39.660355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c3d40028dd'
down_revision = '3bea9c9738c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mod', sa.Column('site_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mod', 'site_page', ['site_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mod', type_='foreignkey')
    op.drop_column('mod', 'site_page_id')
    # ### end Alembic commands ###
