"""empty message

Revision ID: c5cbf6cd0cc4
Revises: ab797a1719fc
Create Date: 2021-05-25 04:41:28.528994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cbf6cd0cc4'
down_revision = 'ab797a1719fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('distance', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('location', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    op.drop_column('item', 'distance')
    # ### end Alembic commands ###
