"""empty message

Revision ID: c8a1cd900af9
Revises: 6a4681f3b437
Create Date: 2021-01-12 04:41:02.962395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8a1cd900af9'
down_revision = '6a4681f3b437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('links', sa.Unicode(), nullable=True))
    op.drop_column('item', 'viewed')
    op.drop_column('item', 'fields')
    op.add_column('user', sa.Column('hide_location', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('show_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_email')
    op.drop_column('user', 'hide_location')
    op.add_column('item', sa.Column('fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('viewed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('item', 'links')
    # ### end Alembic commands ###
