"""empty message

Revision ID: ca7f5a1ed8b9
Revises: 8c92514ae147
Create Date: 2021-11-07 13:59:06.892917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7f5a1ed8b9'
down_revision = '8c92514ae147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('term_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'note', 'term', ['term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'term_id')
    op.drop_column('note', 'subject_id')
    # ### end Alembic commands ###
