"""empty message

Revision ID: d0653ee68aaf
Revises: 9b1fbb39fdef
Create Date: 2021-02-03 01:49:18.603331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0653ee68aaf'
down_revision = '9b1fbb39fdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
