"""empty message

Revision ID: d22f06078edd
Revises: c5cbf6cd0cc4
Create Date: 2021-05-25 05:13:04.350244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22f06078edd'
down_revision = 'c5cbf6cd0cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('custom', sa.JSON(), nullable=True))
    op.drop_column('item', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item', 'custom')
    # ### end Alembic commands ###
