"""empty message

Revision ID: d7965145af64
Revises: 11da9d69cc83
Create Date: 2021-11-06 09:44:05.863591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7965145af64'
down_revision = '11da9d69cc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('author', sa.JSON(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'author')
    # ### end Alembic commands ###
