"""empty message

Revision ID: d9221da7816b
Revises: c8a1cd900af9
Create Date: 2021-01-12 10:39:26.095895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9221da7816b'
down_revision = 'c8a1cd900af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('img_urls', sa.JSON(), nullable=True))
    op.drop_column('item', 'image_urls')
    op.add_column('user', sa.Column('username', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.add_column('item', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('item', 'img_urls')
    # ### end Alembic commands ###
