"""empty message

Revision ID: db3c72c316e5
Revises: d669e2b40f17
Create Date: 2021-03-17 14:59:28.186201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3c72c316e5'
down_revision = 'd669e2b40f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('open', sa.Boolean(), nullable=True))
    op.drop_column('room', 'private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('room', 'open')
    # ### end Alembic commands ###
