"""empty message

Revision ID: deaadf16923c
Revises: a43f0cc922f1
Create Date: 2022-01-07 21:41:45.279475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaadf16923c'
down_revision = 'a43f0cc922f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_saved_users',
    sa.Column('saver', sa.Integer(), nullable=True),
    sa.Column('savee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['savee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['saver'], ['user.id'], )
    )
    op.create_table('_saved_items',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.create_table('saved_items',
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.create_table('message_replies',
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message'], ['message.id'], ),
    sa.ForeignKeyConstraint(['reply'], ['message.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_replies')
    op.drop_table('saved_items')
    op.drop_table('_saved_items')
    op.drop_table('_saved_users')
    # ### end Alembic commands ###
