"""empty message

Revision ID: e397bf84ab8a
Revises: 99ed48965eae
Create Date: 2022-07-06 21:35:31.974768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e397bf84ab8a'
down_revision = '99ed48965eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sub', 'endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub', sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('sub', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
