"""empty message

Revision ID: e4670cfb6938
Revises: 000691be3bbf
Create Date: 2021-12-23 14:21:40.305339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4670cfb6938'
down_revision = '000691be3bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('C')
    op.add_column('user', sa.Column('distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'distance')
    op.create_table('C',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"C_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('taken', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='C_pkey')
    )
    # ### end Alembic commands ###
