"""empty message

Revision ID: e709c3ae8411
Revises: d22f06078edd
Create Date: 2021-05-25 05:17:29.808657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e709c3ae8411'
down_revision = 'd22f06078edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('fields', sa.JSON(), nullable=True))
    op.drop_column('item', 'custom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('custom', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('item', 'fields')
    # ### end Alembic commands ###
