"""empty message

Revision ID: ee422bfc3d70
Revises: 71382e6455de
Create Date: 2021-10-18 09:54:00.470596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee422bfc3d70'
down_revision = '71382e6455de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sitemap_id', sa.Integer(), nullable=True),
    sa.Column('sitemap_index_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sitemap_id'], ['sitemap.id'], ),
    sa.ForeignKeyConstraint(['sitemap_index_id'], ['sitemap_index.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('site_page', sa.Column('sitemap_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site_page', 'sitemap', ['sitemap_id'], ['id'])
    op.drop_column('site_page', 'changefreq')
    op.drop_column('site_page', 'lastmod')
    op.add_column('sitemap', sa.Column('type', sa.Unicode(), nullable=True))
    op.drop_constraint('sitemap_index_id_fkey', 'sitemap', type_='foreignkey')
    op.drop_column('sitemap', 'index_id')
    op.drop_constraint('user_sitemap_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'lastmod')
    op.drop_column('user', 'sitemap_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sitemap_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('lastmod', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_sitemap_id_fkey', 'user', 'sitemap', ['sitemap_id'], ['id'])
    op.add_column('sitemap', sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sitemap_index_id_fkey', 'sitemap', 'sitemap_index', ['index_id'], ['id'])
    op.drop_column('sitemap', 'type')
    op.add_column('site_page', sa.Column('lastmod', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('site_page', sa.Column('changefreq', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'site_page', type_='foreignkey')
    op.drop_column('site_page', 'sitemap_id')
    op.drop_table('mod')
    # ### end Alembic commands ###
