"""empty message

Revision ID: f294f10f796d
Revises: f4cb90201399
Create Date: 2021-03-19 04:01:55.187601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f294f10f796d'
down_revision = 'f4cb90201399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'visible')
    op.add_column('user', sa.Column('unseen_rooms', sa.JSON(), nullable=True))
    op.drop_column('user', 'seen_rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('seen_rooms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'unseen_rooms')
    op.add_column('room', sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
