"""empty message

Revision ID: f4cb90201399
Revises: 205a147122ab
Create Date: 2021-03-19 03:39:34.143217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cb90201399'
down_revision = '205a147122ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('in_rooms', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('seen_rooms', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seen_rooms')
    op.drop_column('user', 'in_rooms')
    # ### end Alembic commands ###
