"""empty message

Revision ID: f627f01f7a45
Revises: 4bfbcb324f07
Create Date: 2021-03-14 00:58:37.725713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f627f01f7a45'
down_revision = '4bfbcb324f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'location')
    op.drop_column('user', 'closedby')
    op.drop_column('user', 'code')
    op.drop_column('user', 'email')
    op.drop_column('user', 'distance')
    op.drop_column('user', 'save_count')
    op.drop_column('user', 'subscribed')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'openby')
    op.drop_column('user', 'customer_code')
    op.drop_column('user', 'show_email')
    op.drop_column('user', 'card')
    op.drop_column('user', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('card', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('show_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('customer_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('openby', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('save_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('closedby', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
