"""empty message

Revision ID: f951bb2016a4
Revises: 673bb5aad451
Create Date: 2022-01-12 19:47:48.292915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f951bb2016a4'
down_revision = '673bb5aad451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_items',
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child'], ['item.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['item.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_items')
    # ### end Alembic commands ###
