"""empty message

Revision ID: fd11a1f01786
Revises: 9ccb4dfda317
Create Date: 2021-02-01 00:22:25.356873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd11a1f01786'
down_revision = '9ccb4dfda317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logo', sa.Unicode(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'logo')
    # ### end Alembic commands ###
